plugins: {}
filters:
  # https://github.com/textlint/textlint-filter-rule-comments
  comments: true
  # https://github.com/textlint/textlint-filter-rule-allowlist
  allowlist:
    allow:
      - "/^:::details .+$/m"
rules:
  # https://github.com/textlint-ja/textlint-rule-preset-ja-technical-writing
  preset-ja-technical-writing:
    # https://github.com/textlint-ja/textlint-rule-ja-no-mixed-period
    ja-no-mixed-period:
      allowPeriodMarks:
        - "、"
    ja-no-redundant-expression:
      dictOptions:
        dict1:
          allows:
            - "/^することも可能です$/"
        dict2:
          allows:
            - "/^することもできます$/"
    # https://github.com/textlint-ja/textlint-rule-no-exclamation-question-mark
    no-exclamation-question-mark: false
    # https://github.com/textlint-ja/textlint-rule-ja-no-successive-word
    ja-no-successive-word:
      allow:
        - "！"
  # https://github.com/textlint-rule/textlint-rule-no-todo
  no-todo: true
  # https://github.com/bun913/textlint-rule-aws-service-name
  aws-service-name: true
