name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unused-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: bun run check:unused-images
